'''Entry point into the agents module set'''
from .base_agent import BaseAgent
from .docker_agent import DockerAgent
from .player_agent import PlayerAgent
from .random_agent import RandomAgent
from .simple_agent import SimpleAgent
from .tensorforce_agent import TensorForceAgent
#from .dqn_agent import DqnAgent
#from .d_rec_qn_agent import DrqnAgent
from .bilal_ccritic_bignn import bilal_ccritic_bignnAgent
from .bilal_ccritic_bignn_alt import bilal_ccritic_bignn_Alt_Agent
from .static_agent import StaticAgent
from .uct_agent import UctAgent
from .simple_agent_nobombs import SimpleAgentNoBombs
from .demonstrator_agent import DemonstratorAgent
from .simple_agent_epsilon import SimpleAgentEpsilon
from .rules_random_agent import RulesRandomAgent
from .random_agent_no_bomb import RandomAgentNoBombs
from .rules_random_nobomb import RulesRandomAgentNoBomb
